language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
- composer install --no-interaction --prefer-dist
- echo 'date.timezone = "Australia/Sydney"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: vendor/bin/phpunit --colors  --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
